[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.0",
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "pyjwt[crypto]>=2.10.1",
    "uvicorn>=0.35.0",
]
